[package]
name = "Originmate"
version = "1.8.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
originmate = "0x0"
# originmate = "0xab3596285e7d3c7ca1ae2a799f52625435d3df1c"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.19.0
rev = "a8af20d94e951ecfb6d0cd47c23cf6393013d8a8"
